### ISSUE TITLE
Feature request: JSON output

### ISSUE THREAD

**Issue by haakonstorm** [engvik/sbanken-cli#24]
`sbanken-cli --output json` would be very useful for usage in e.g. shell scripts.

**Comment by engvik** [comment]
Great idea :smile: I'll try to get around to add it soon, unless you want to provide a PR yourself.

**Comment by engvik** [comment]
Released in 1.5.0 :+1:

**Comment by haakonstorm** [comment]
Awesome ork. Gonna give this a shot asap. 
[I have a particular feature I'd like to try and use `sbanken-cli` for, but I realize perhaps peoples over than myself might find it useful, and its functionality (perhaps!) belongs inside a first order tool like `sbanken-cli`. [I snipped this out and made a separate feature request from it - just close it straight away if you feel it is foreign to this cli tools aims!)
