### ISSUE TITLE
Feature request: collapse all accounts, match & remove internal transfers

### ISSUE THREAD

**Issue by haakonstorm** [engvik/sbanken-cli#29]
Assume account A, B and C.

Transfer 15$ from account A to account B.

Now you have an entry `-15$` in account A, 
*and* an entry `+15$` in account B.

But, you still have the exact same amount of cash, sum total! Just more noise in your finances.

I'm looking to collapse ("merge") all/select individual accounts. 
Then, find pairs of "matching internal transfers" and remove them. 
In the end, if I [still] have a mortgage on my house (in the same bank), 
my sum total *should* be negative, right? See the use case?

**Comment by engvik** [comment]
Initial thought was to expose the sbanken API through the command line, but I guess there aren't any reasons to add other functionality for convenience either. Maybe expose them through a sub command.

Do you have any thoughts on how this should be invoked? Maybe a be a separate command with date range filters?

**Comment by haakonstorm** [comment]
I've been thinking about this from a few different perspectives.
I tend to come back to the same answer. 

Oftentimes we spend time coding or scripting what takes less time manually. In this case, logging in to sbanken, then boogie around in the web UI. But sometimes we *can* re-use that little pipeline, sometimes we think its worth sharing. 
Elon Musks entire "x.com" venture solved and automated a lot of really complex problems. But, the only thing people really wanted, was this "tiny" feature: to e-mail money; *paypal*. I can't help but recognize the similarities here. Hear me out. We're essentially taking something inherently "easy" (sbanken.no web UI), and "complicating" it (sbanken-cli, JSON, cmd line args). 

The cool part about complicating, is gaining the new option to also re-assemble; over and over. Oftentimes we who are knee-deep in the complexities, are the last to see the new options only now available. 

For example: consider the following hypothetical command and its output. I use `main` to call the binary and not `sbanken-cli` as I dutifully follow your `USAGE` clause way down in `readme.md`😉

```
λ main --json status

{"balance": "-220413,23"}
```

What `sbanken-cli` (I mean, `main`) did here, was compute my net worth. 
To do that, it had to fetch and sum all my different accounts *and* my loan(s). 
What is interesting, is that because with the way we do modern finance, this negative amount *isn't* particularly useful to *anyone*, even me. 
This is fact because I *can* still go to an ATM and withdraw cash. 
(After properly disinfecting the keypad with n-benzene alcohol. Then entering my 15 1/2 bit long PIN cipher. And *then* get the virus because, you know, nobody disinfected the *cash*.)

Anyways, this exercise actually surface a couple of things. 
Firstly, the sad state of hand hygiene in our little nation. 
Secondly, that we need some intuitive way to verbalize and rationalize over .. money. 
And lastly, that this tool of yours, `main`, actually potentially enables "ordinary users" to simplify tasks everybody does, almost every day. "Did my paycheck arrive yet"? "Whats my balance"? "Pay eFaktura X". "Send cash to Y". 
I'm not talking about `sbanken-cli` mushrooming to a gui, but implementing enough 'magic' for the tool to actually deliver on the `-cli` promise. Lets assume we spec this 'magic' in extremely simple terms, like speccing a "Markdown for norwegian banking" of sorts. Who knows, when "danskebank-cli" and "landkredittbank-cli" manifest, they adopt `Pengvikdown` or `Engvikonomy` as well. Slowly, over time, features emerge, like the one described above. When you transfer from one account to another, those two transactions can be matched and then removed. Likewise, when you transfer from `sbanken` to `postbanken` those two transactions can also be matched and removed. Little by little. This is way too long already, and you've already stated you only intended to essentially only wrap the `sbanken api json` in a cli and be done, so I'll end here. `sbanken-cli` is awesome already.  

But to round off and arrive full circle at the Elon Musk reference:  If both you and I are `main`-equipped, we can do stuff like "*you e-mailing me a request for cash*". By daemonizing `sbanken-cli` and scripting some simple polling and such, events like deposits of cash can be relayed to a notification, to a `telegram–cli` bot that asks me yes/no on eFaktura Y, you get the idea. I guess my point is that some tool need to become the defacto tool to be relied upon for day to day stuff.
